name: CI/CD

# ci configurado para instalar pendências e rodar pytest
on:
  pull_request:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Black (check)
        run: black --check .

      - name: Flake8
        run: flake8 .

      - name: Pytest
        run: pytest --cov=src --cov-report=xml
